---
name: Lambda Responder

on:
    workflow_dispatch:
        inputs:
            design:
                description: Name of the design
            payload:
                description: The JSON as a string payload from flightcenter

jobs:
    explore:
        name: Explore inputs
        runs-on: ubuntu-latest

        steps:
            - name: Check Out Repository
              uses: actions/checkout@v3
              with:
                    fetch-depth: 0

            - name: Show Inputs
              shell: bash
              run: |
                echo input design = ${{ inputs.design }}
                echo input payload = ${{ inputs.payload }}
            - name: Environment
              shell: bash
              run: |
                echo "Environment"
                env | sort
